use_frameworks!

target 'MarkdownAttributedString_Example' do
  pod 'MarkdownAttributedString', :path => '../'

  target 'MarkdownAttributedString_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  end
end
